<?php
    include('_inc/classes/Date.php');
    include('_inc/classes/Menu.php');
    include('_inc/classes/Assets.php');
    include('_inc/classes/Contact.php');
    require('_inc/classes/Database.php');
    include('_inc/classes/User.php');
    require('_inc/classes/Auth.php');
    include('_inc/classes/Product.php');
    include('_inc/classes/Faq.php');
    include('_inc/classes/Order.php');
?>